package yara

import (
	"fmt"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/muxover/goripper/internal/output"
)

const (
	maxStringConditions = 30
	minStringLen        = 12
)

// Generate produces a YARA rule from an analysis result.
// The rule targets the binary's format (PE or ELF).
func Generate(result *output.AnalysisResult) string {
	var sb strings.Builder

	ruleName := sanitizeName(result.BinaryInfo.Path)
	if ruleName == "" {
		ruleName = "GoRipper_sample"
	}

	candidates := selectStrings(result)

	sb.WriteString(fmt.Sprintf("rule %s {\n", ruleName))
	sb.WriteString("    meta:\n")
	sb.WriteString("        description = \"Auto-generated by GoRipper v0.4.0\"\n")
	if result.BinaryInfo.GoVersion != "" {
		sb.WriteString(fmt.Sprintf("        go_version  = %q\n", result.BinaryInfo.GoVersion))
	}
	sb.WriteString(fmt.Sprintf("        obfuscation = \"%.2f\"\n", result.BinaryInfo.ObfuscationScore))
	sb.WriteString(fmt.Sprintf("        date        = %q\n", time.Now().Format("2006-01-02")))

	if len(candidates) == 0 {
		sb.WriteString("    condition:\n")
		sb.WriteString(fmt.Sprintf("        %s\n", formatCondition(result.BinaryInfo.Format)))
		sb.WriteString("}\n")
		return sb.String()
	}

	sb.WriteString("    strings:\n")
	for i, s := range candidates {
		sb.WriteString(fmt.Sprintf("        $s%d = %s\n", i, formatString(s)))
	}

	sb.WriteString("    condition:\n")
	minMatch := 2
	if len(candidates) == 1 {
		minMatch = 1
	}
	sb.WriteString(fmt.Sprintf("        %s and %d of ($s*)\n",
		formatCondition(result.BinaryInfo.Format), minMatch))
	sb.WriteString("}\n")

	return sb.String()
}

func selectStrings(result *output.AnalysisResult) []string {
	var selected []string
	seen := make(map[string]bool)

	// Priority 1: URL and secret strings — high signal, unique
	for _, s := range result.Strings {
		if len(selected) >= maxStringConditions {
			break
		}
		if s.Type != "url" && s.Type != "secret" {
			continue
		}
		if !isYaraCandidate(s.Value) || seen[s.Value] {
			continue
		}
		seen[s.Value] = true
		selected = append(selected, s.Value)
	}

	// Priority 2: path strings (non-stdlib, non-runtime)
	for _, s := range result.Strings {
		if len(selected) >= maxStringConditions {
			break
		}
		if s.Type != "path" {
			continue
		}
		if !isYaraCandidate(s.Value) || seen[s.Value] || isStdlibPath(s.Value) {
			continue
		}
		seen[s.Value] = true
		selected = append(selected, s.Value)
	}

	// Priority 3: function name hashes for obfuscated binaries (garble score > 0.5)
	if result.BinaryInfo.ObfuscationScore > 0.5 {
		for _, fn := range result.Functions {
			if len(selected) >= maxStringConditions {
				break
			}
			if fn.PackageKind != "user" || fn.FunctionSource != "pclntab" {
				continue
			}
			if len(fn.Name) < minStringLen || seen[fn.Name] {
				continue
			}
			seen[fn.Name] = true
			selected = append(selected, fn.Name)
		}
	}

	return selected
}

func isYaraCandidate(s string) bool {
	if len(s) < minStringLen {
		return false
	}
	if !utf8.ValidString(s) {
		return false
	}
	printable := 0
	for _, r := range s {
		if r >= 0x20 && r < 0x7f {
			printable++
		}
	}
	return printable*10 >= len(s)*8
}

func isStdlibPath(s string) bool {
	stdlibPrefixes := []string{
		"runtime/", "reflect/", "sync/", "fmt/", "os/", "io/",
		"net/", "encoding/", "crypto/", "math/", "sort/",
		"strings/", "bytes/", "bufio/", "log/", "time/",
		"github.com/", "golang.org/",
	}
	for _, p := range stdlibPrefixes {
		if strings.HasPrefix(s, p) {
			return true
		}
	}
	return false
}

func formatCondition(format string) string {
	switch strings.ToLower(format) {
	case "pe", "pe32", "pe32+":
		return "uint16(0) == 0x5A4D"
	case "elf":
		return "uint32(0) == 0x464C457F"
	default:
		return "uint16(0) == 0x5A4D or uint32(0) == 0x464C457F"
	}
}

func formatString(s string) string {
	safe := strings.ReplaceAll(s, "\\", "\\\\")
	safe = strings.ReplaceAll(safe, "\"", "\\\"")
	safe = strings.ReplaceAll(safe, "\n", "\\n")
	safe = strings.ReplaceAll(safe, "\r", "\\r")
	safe = strings.ReplaceAll(safe, "\t", "\\t")
	return fmt.Sprintf("%q", safe)
}

func sanitizeName(path string) string {
	name := path
	for i := len(path) - 1; i >= 0; i-- {
		if path[i] == '/' || path[i] == '\\' {
			name = path[i+1:]
			break
		}
	}
	if dot := strings.LastIndex(name, "."); dot > 0 {
		name = name[:dot]
	}

	var sb strings.Builder
	for _, r := range name {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_' {
			sb.WriteRune(r)
		} else {
			sb.WriteByte('_')
		}
	}
	result := sb.String()
	// YARA rule names cannot start with a digit
	if len(result) > 0 && result[0] >= '0' && result[0] <= '9' {
		result = "rule_" + result
	}
	if result == "" {
		return "GoRipper_sample"
	}
	return result
}
