package decompile

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/muxover/goripper/internal/ir"
	"github.com/muxover/goripper/internal/version"
)

type Options struct {
	OutDir string
	Lang   string // "c" (default) or "go"
}

func Emit(funcs []*ir.IRFunc, opts Options) error {
	if err := os.MkdirAll(opts.OutDir, 0o755); err != nil {
		return fmt.Errorf("create output dir: %w", err)
	}

	byPkg := make(map[string][]*ir.IRFunc)
	for _, f := range funcs {
		pkg := sanitizePkgName(f.Package)
		byPkg[pkg] = append(byPkg[pkg], f)
	}

	stubSet := make(map[string]bool)

	pkgs := sortedKeys(byPkg)
	for _, pkg := range pkgs {
		fns := byPkg[pkg]
		path := filepath.Join(opts.OutDir, pkg+".c")
		if err := writeCFile(path, pkg, fns, stubSet); err != nil {
			return fmt.Errorf("write %s: %w", path, err)
		}
	}

	if err := writeStructsHeader(opts.OutDir); err != nil {
		return fmt.Errorf("write structs.h: %w", err)
	}
	if err := writeStubsHeader(opts.OutDir, stubSet); err != nil {
		return fmt.Errorf("write stubs.h: %w", err)
	}
	return nil
}

func writeCFile(path, pkg string, fns []*ir.IRFunc, stubSet map[string]bool) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	w := &writer{w: f}
	w.line("// Auto-generated by GoRipper %s — do not edit manually.", version.Version)
	w.line("#include \"structs.h\"")
	w.line("#include \"stubs.h\"")
	w.line("")

	for _, fn := range fns {
		emitFunc(w, fn, stubSet)
		w.line("")
	}
	return w.err
}

func emitFunc(w *writer, f *ir.IRFunc, stubSet map[string]bool) {
	cName := cFuncName(f.Name)

	params := make([]string, len(f.Params))
	for i, p := range f.Params {
		typ := f.Vars[p]
		if typ == "" {
			typ = "int64_t"
		}
		params[i] = fmt.Sprintf("%s %s", typ, p)
	}

	retType := funcReturnType(f)

	w.line("// 0x%x  %s", f.Addr, f.Name)
	if len(params) == 0 {
		w.line("%s %s(void) {", retType, cName)
	} else {
		w.line("%s %s(%s) {", retType, cName, strings.Join(params, ", "))
	}

	paramSet := make(map[string]bool, len(f.Params))
	for _, p := range f.Params {
		paramSet[p] = true
	}
	locals := collectLocals(f, paramSet)
	for _, loc := range locals {
		typ := f.Vars[loc]
		if typ == "" {
			typ = "int64_t"
		}
		w.line("    %s %s;", typ, loc)
	}
	if len(locals) > 0 {
		w.line("")
	}

	for bi, blk := range f.Blocks {
		// Emit label if this block has predecessors or is not the entry block.
		if bi > 0 || len(blk.Preds) > 0 {
			w.line("%s:", blk.Label)
		}
		for _, instr := range blk.Instrs {
			emitInstr(w, instr, stubSet)
		}
	}

	w.line("}")
}

func emitInstr(w *writer, instr ir.IRInstr, stubSet map[string]bool) {
	switch instr.Op {
	case ir.OpAssign:
		if len(instr.Src) > 0 {
			w.line("    %s = %s;", instr.Dst, instr.Src[0])
		}

	case ir.OpLoad:
		if len(instr.Src) > 0 {
			addr := instr.Src[0]
			w.line("    %s = *((int64_t*)(%s));", instr.Dst, addr)
		}

	case ir.OpStore:
		if len(instr.Src) > 0 {
			w.line("    *((int64_t*)(%s)) = %s;", instr.Dst, instr.Src[0])
		}

	case ir.OpArith:
		if len(instr.Src) >= 2 {
			op := arithOp(instr.Meta)
			w.line("    %s = %s %s %s;", instr.Dst, instr.Src[0], op, instr.Src[1])
		}

	case ir.OpUnary:
		if len(instr.Src) > 0 {
			op := unaryOp(instr.Meta)
			w.line("    %s = %s%s;", instr.Dst, op, instr.Src[0])
		}

	case ir.OpCall:
		cTarget := cFuncName(instr.Target)
		if stubSet != nil && !strings.HasPrefix(instr.Target, "(*") {
			stubSet[instr.Target] = true
		}
		args := strings.Join(instr.Src, ", ")
		if instr.Dst != "" && instr.Dst != "_ret" {
			w.line("    %s = %s(%s);", instr.Dst, cTarget, args)
		} else {
			w.line("    %s(%s);", cTarget, args)
		}

	case ir.OpPhi:
		if len(instr.Src) > 0 {
			w.line("    %s = %s; /* phi */", instr.Dst, instr.Src[0])
		}

	case ir.OpIf:
		w.line("    if (%s) goto %s; else goto %s;", instr.Meta, instr.Label, instr.Label2)

	case ir.OpGoto:
		w.line("    goto %s;", instr.Label)

	case ir.OpReturn:
		if len(instr.Src) > 0 {
			w.line("    return %s;", strings.Join(instr.Src, ", "))
		} else {
			w.line("    return;")
		}

	case ir.OpLabel:
		// Labels are emitted at block boundaries, not per-instruction.

	case ir.OpComment:
		w.line("    /* %s */", instr.Meta)
	}
}

func writeStructsHeader(outDir string) error {
	path := filepath.Join(outDir, "structs.h")
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	w := &writer{w: f}
	w.line("// Auto-generated by GoRipper %s", version.Version)
	w.line("#pragma once")
	w.line("#include <stdint.h>")
	w.line("")
	w.line("// Go runtime type representations")
	w.line("typedef struct { char *ptr; int64_t len; }              GoString;")
	w.line("typedef struct { void *ptr; int64_t len; int64_t cap; } GoSlice;")
	w.line("typedef struct { void *type_; void *data; }             GoIface;")
	w.line("typedef struct { void *type_; }                         _type;")
	w.line("typedef GoIface error;")
	w.line("")
	return w.err
}

func writeStubsHeader(outDir string, stubSet map[string]bool) error {
	path := filepath.Join(outDir, "stubs.h")
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	w := &writer{w: f}
	w.line("// Auto-generated by GoRipper %s — fill in stubs to compile.", version.Version)
	w.line("#pragma once")
	w.line("#include \"structs.h\"")
	w.line("")
	w.line("// External function stubs — declare or implement these to compile.")

	stubs := sortedKeys(stubSet)
	for _, name := range stubs {
		cName := cFuncName(name)
		w.line("extern int64_t %s(...);  /* %s */", cName, name)
	}
	w.line("")
	return w.err
}

func collectLocals(f *ir.IRFunc, paramSet map[string]bool) []string {
	seen := make(map[string]bool)
	var locals []string
	for _, blk := range f.Blocks {
		for _, instr := range blk.Instrs {
			if instr.Dst == "" || paramSet[instr.Dst] || seen[instr.Dst] {
				continue
			}
			if instr.Op == ir.OpLabel || instr.Op == ir.OpComment || instr.Op == ir.OpGoto || instr.Op == ir.OpReturn || instr.Op == ir.OpIf || instr.Op == ir.OpStore {
				continue
			}
			// Skip destinations that are memory expressions, not variable names.
			if strings.Contains(instr.Dst, "(") || strings.Contains(instr.Dst, "*") {
				continue
			}
			seen[instr.Dst] = true
			locals = append(locals, instr.Dst)
		}
	}
	sort.Strings(locals)
	return locals
}

func funcReturnType(f *ir.IRFunc) string {
	for _, blk := range f.Blocks {
		for _, instr := range blk.Instrs {
			if instr.Op == ir.OpReturn {
				if len(instr.Src) > 0 {
					if t := f.Vars[instr.Src[0]]; t != "" {
						return t
					}
					return "int64_t"
				}
				return "void"
			}
		}
	}
	return "void"
}

func sanitizePkgName(pkg string) string {
	if i := strings.LastIndex(pkg, "/"); i >= 0 {
		pkg = pkg[i+1:]
	}
	var sb strings.Builder
	for _, c := range pkg {
		if (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_' {
			sb.WriteRune(c)
		} else {
			sb.WriteByte('_')
		}
	}
	s := sb.String()
	if s == "" {
		return "pkg"
	}
	return s
}

func cFuncName(name string) string {
	// Indirect call via register.
	if strings.HasPrefix(name, "(*") {
		return strings.NewReplacer("(*", "", ")", "").Replace(name)
	}
	var sb strings.Builder
	for _, c := range name {
		if (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_' {
			sb.WriteRune(c)
		} else {
			sb.WriteByte('_')
		}
	}
	s := sb.String()
	if s == "" || (s[0] >= '0' && s[0] <= '9') {
		s = "fn_" + s
	}
	return s
}

func arithOp(meta string) string {
	switch meta {
	case "add":
		return "+"
	case "sub":
		return "-"
	case "mul":
		return "*"
	case "div":
		return "/"
	case "and":
		return "&"
	case "or":
		return "|"
	case "xor":
		return "^"
	case "shl", "sal":
		return "<<"
	case "shr", "sar":
		return ">>"
	default:
		return meta
	}
}

func unaryOp(meta string) string {
	switch meta {
	case "neg":
		return "-"
	case "not":
		return "~"
	default:
		return meta
	}
}

func sortedKeys[K ~string, V any](m map[K]V) []K {
	keys := make([]K, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Slice(keys, func(i, j int) bool { return keys[i] < keys[j] })
	return keys
}

// writer is a small helper that tracks the first write error.
type writer struct {
	w   *os.File
	err error
}

func (w *writer) line(format string, args ...any) {
	if w.err != nil {
		return
	}
	_, w.err = fmt.Fprintf(w.w, format+"\n", args...)
}
