package decompile

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/muxover/goripper/internal/ir"
	"github.com/muxover/goripper/internal/version"
)

// runtimeLiftedCalls are emitted as Go idioms by emitGoCall.
// They are excluded from stub generation since they map to built-in Go syntax.
var runtimeLiftedCalls = map[string]bool{
	"runtime.gopanic":        true,
	"runtime.gorecover":      true,
	"runtime.newproc":        true,
	"runtime.deferprocStack": true,
	"runtime.deferproc":      true,
	"runtime.deferreturn":    true,
	"runtime.chansend1":      true,
	"runtime.chanrecv1":      true,
	"runtime.makeslice":      true,
	"runtime.makemap":        true,
	"runtime.makechan":       true,
	"runtime.convT2I":        true,
	"runtime.convT64":        true,
	"runtime.convTstring":    true,
}

// EmitGo produces a compilable Go module under opts.OutDir.
// One subdirectory per user package; go.mod at the root.
// Per-package stubs.go holds stub bodies for all unresolved external calls.
func EmitGo(funcs []*ir.IRFunc, opts Options) error {
	if err := os.MkdirAll(opts.OutDir, 0o755); err != nil {
		return fmt.Errorf("create output dir: %w", err)
	}

	byPkg := make(map[string][]*ir.IRFunc)
	for _, f := range funcs {
		byPkg[f.Package] = append(byPkg[f.Package], f)
	}

	pkgSet := make(map[string]bool, len(byPkg))
	for pkg := range byPkg {
		pkgSet[pkg] = true
	}

	for _, pkg := range sortedKeys(byPkg) {
		fns := byPkg[pkg]
		pkgDir := filepath.Join(opts.OutDir, goPackageDir(pkg))
		if err := os.MkdirAll(pkgDir, 0o755); err != nil {
			return fmt.Errorf("mkdir %s: %w", pkgDir, err)
		}
		short := goShortPkg(pkg)

		goFile := filepath.Join(pkgDir, short+".go")
		if err := writeGoFile(goFile, short, fns); err != nil {
			return fmt.Errorf("write %s: %w", goFile, err)
		}

		stubs := collectGoStubs(fns, pkgSet)
		if len(stubs) > 0 {
			stubFile := filepath.Join(pkgDir, "stubs.go")
			if err := writeGoStubFile(stubFile, short, stubs); err != nil {
				return fmt.Errorf("write stubs %s: %w", stubFile, err)
			}
		}
	}

	return writeGoMod(opts.OutDir)
}

func writeGoFile(path, pkgName string, fns []*ir.IRFunc) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	w := &writer{w: f}
	w.line("// Code generated by GoRipper %s — structural aid, not original source.", version.Version)
	w.line("package %s", pkgName)
	w.line("")
	w.line("import \"unsafe\"")
	w.line("")
	w.line("var _ unsafe.Pointer // keep import active")
	w.line("")

	nameCount := make(map[string]int)
	for _, fn := range fns {
		emitGoFunc(w, fn, nameCount)
		w.line("")
	}

	// main package must have func main() to link as an executable.
	if pkgName == "main" && !hasGoMain(fns) {
		w.line("func main() {}")
		w.line("")
	}

	return w.err
}

func emitGoFunc(w *writer, f *ir.IRFunc, nameCount map[string]int) {
	short := goFuncShortName(f.Name)
	if n := nameCount[short]; n > 0 {
		short = fmt.Sprintf("%s_%d", short, n)
	}
	nameCount[goFuncShortName(f.Name)]++

	params := make([]string, len(f.Params))
	for i, p := range f.Params {
		params[i] = p + " " + goType(f.Vars[p])
	}
	retType := goFuncReturnType(f)

	w.line("// 0x%x %s", f.Addr, f.Name)
	sig := fmt.Sprintf("func %s(%s)", short, strings.Join(params, ", "))
	if retType != "" {
		sig += " " + retType
	}
	w.line("%s {", sig)

	paramSet := make(map[string]bool, len(f.Params))
	for _, p := range f.Params {
		paramSet[p] = true
	}
	locals := collectGoLocals(f, paramSet)
	if len(locals) > 0 {
		w.line("\tvar (")
		for _, loc := range locals {
			w.line("\t\t%s %s", loc, goType(f.Vars[loc]))
		}
		w.line("\t)")
		// Prevent "declared but not used" errors — reconstructed code may not
		// read every SSA variable on all code paths.
		uses := make([]string, len(locals))
		copy(uses, locals)
		w.line("\t_ = []any{%s}", strings.Join(uses, ", "))
	}

	refd := collectReferencedLabels(f)
	for bi, blk := range f.Blocks {
		if bi > 0 && refd[blk.Label] {
			w.line("%s:", blk.Label)
		}
		for _, instr := range blk.Instrs {
			emitGoInstr(w, instr, f)
		}
	}

	w.line("}")
}

func emitGoInstr(w *writer, instr ir.IRInstr, f *ir.IRFunc) {
	switch instr.Op {
	case ir.OpAssign:
		if len(instr.Src) > 0 {
			w.line("\t%s = %s", instr.Dst, instr.Src[0])
		}

	case ir.OpLoad:
		if len(instr.Src) > 0 {
			src := instr.Src[0]
			typ := goType(f.Vars[instr.Dst])
			if strings.ContainsAny(src, "(*") {
				w.line("\t// load %s = *(%s)", instr.Dst, src)
			} else {
				// uintptr round-trip is safe here: we need a numeric address, not a pointer the GC tracks.
				w.line("\t%s = *(*%s)(unsafe.Pointer(uintptr(%s)))", instr.Dst, typ, src)
			}
		}

	case ir.OpStore:
		if len(instr.Src) > 0 {
			dst := instr.Dst
			if strings.ContainsAny(dst, "(*") {
				w.line("\t// store *(%s) = %s", dst, instr.Src[0])
			} else {
				w.line("\t*(*int64)(unsafe.Pointer(uintptr(%s))) = %s", dst, instr.Src[0])
			}
		}

	case ir.OpArith:
		if len(instr.Src) >= 2 {
			w.line("\t%s = %s %s %s", instr.Dst, instr.Src[0], goArithOp(instr.Meta), instr.Src[1])
		}

	case ir.OpUnary:
		if len(instr.Src) > 0 {
			w.line("\t%s = %s%s", instr.Dst, goUnaryOp(instr.Meta), instr.Src[0])
		}

	case ir.OpCall:
		emitGoCall(w, instr)

	case ir.OpPhi:
		if len(instr.Src) > 0 {
			w.line("\t%s = %s // phi", instr.Dst, instr.Src[0])
		}

	case ir.OpIf:
		w.line("\tif %s { goto %s } else { goto %s }", instr.Meta, instr.Label, instr.Label2)

	case ir.OpGoto:
		w.line("\tgoto %s", instr.Label)

	case ir.OpReturn:
		if len(instr.Src) > 0 {
			w.line("\treturn %s", strings.Join(instr.Src, ", "))
		} else {
			w.line("\treturn")
		}

	case ir.OpLabel:
		// block labels are emitted at the block boundary

	case ir.OpComment:
		w.line("\t// %s", instr.Meta)
	}
}

func emitGoCall(w *writer, instr ir.IRInstr) {
	args, dst := instr.Src, instr.Dst

	switch instr.Target {
	case "runtime.gopanic":
		val := "nil"
		if len(args) > 0 {
			val = args[0]
		}
		w.line("\tpanic(%s)", val)
		return

	case "runtime.gorecover":
		if dst != "" {
			w.line("\t%s = recover()", dst)
		} else {
			w.line("\trecover()")
		}
		return

	case "runtime.newproc":
		// fn is a runtime closure pointer; recovering the name requires call graph data.
		fn := "nil"
		if len(args) >= 2 {
			fn = args[1]
		}
		w.line("\tgo func() { _ = %s }() // runtime.newproc", fn)
		return

	case "runtime.deferprocStack", "runtime.deferproc":
		fn := "nil"
		if len(args) >= 2 {
			fn = args[1]
		}
		w.line("\tdefer func() { _ = %s }() // runtime.deferproc", fn)
		return

	case "runtime.deferreturn":
		// Implicit in Go — the compiler inserts deferreturn automatically.
		return

	case "runtime.chansend1":
		ch, val := "nil", "nil"
		if len(args) >= 1 {
			ch = args[0]
		}
		if len(args) >= 2 {
			val = args[1]
		}
		w.line("\t%s <- %s", ch, val)
		return

	case "runtime.chanrecv1":
		ch := "nil"
		if len(args) >= 1 {
			ch = args[0]
		}
		if dst != "" {
			w.line("\t%s = <-%s", dst, ch)
		} else {
			w.line("\t<-%s", ch)
		}
		return

	case "runtime.makeslice":
		lenArg, capArg := "0", "0"
		if len(args) >= 2 {
			lenArg = args[1]
		}
		if len(args) >= 3 {
			capArg = args[2]
		}
		if dst != "" {
			w.line("\t%s = make([]byte, %s, %s)", dst, lenArg, capArg)
		}
		return

	case "runtime.makemap":
		if dst != "" {
			w.line("\t%s = make(map[any]any)", dst)
		}
		return

	case "runtime.makechan":
		size := "0"
		if len(args) >= 2 {
			size = args[1]
		}
		if dst != "" {
			w.line("\t%s = make(chan any, %s)", dst, size)
		}
		return

	case "runtime.convT2I", "runtime.convT64", "runtime.convTstring":
		if dst != "" && len(args) > 0 {
			w.line("\t%s = any(%s) // interface conversion", dst, args[0])
		}
		return
	}

	fnName := goCallName(instr.Target)
	argsStr := strings.Join(args, ", ")
	if dst != "" && dst != "_ret" {
		w.line("\t%s = %s(%s)", dst, fnName, argsStr)
	} else {
		w.line("\t%s(%s)", fnName, argsStr)
	}
}

func writeGoStubFile(path, pkgName string, stubs []goStub) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	w := &writer{w: f}
	w.line("// Code generated by GoRipper %s — implement stubs to compile fully.", version.Version)
	w.line("package %s", pkgName)
	w.line("")
	for _, s := range stubs {
		params := make([]string, s.nArgs)
		for i := range params {
			params[i] = fmt.Sprintf("a%d any", i)
		}
		ret := ""
		if s.hasRet {
			ret = " any"
		}
		w.line("// %s", s.origName)
		w.line("func %s(%s)%s { panic(\"stub\") }", s.goName, strings.Join(params, ", "), ret)
		w.line("")
	}
	return w.err
}

func writeGoMod(outDir string) error {
	path := filepath.Join(outDir, "go.mod")
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	w := &writer{w: f}
	w.line("// Generated by GoRipper %s", version.Version)
	w.line("module recovered")
	w.line("")
	w.line("go 1.21")
	w.line("")
	return w.err
}

type goStub struct {
	origName string
	goName   string
	nArgs    int
	hasRet   bool
}

func collectGoStubs(fns []*ir.IRFunc, pkgSet map[string]bool) []goStub {
	seen := make(map[string]*goStub)

	for _, f := range fns {
		for _, blk := range f.Blocks {
			for _, instr := range blk.Instrs {
				if instr.Op != ir.OpCall || instr.Target == "" {
					continue
				}
				if runtimeLiftedCalls[instr.Target] {
					continue
				}
				isInternal := false
				for pkg := range pkgSet {
					if strings.HasPrefix(instr.Target, pkg+".") || instr.Target == pkg {
						isInternal = true
						break
					}
				}
				if isInternal {
					continue
				}

				goName := goCallName(instr.Target)
				nArgs := len(instr.Src)
				hasRet := instr.Dst != "" && instr.Dst != "_ret"

				if s, ok := seen[goName]; ok {
					if nArgs > s.nArgs {
						s.nArgs = nArgs
					}
					if hasRet {
						s.hasRet = true
					}
				} else {
					seen[goName] = &goStub{origName: instr.Target, goName: goName, nArgs: nArgs, hasRet: hasRet}
				}
			}
		}
	}

	out := make([]goStub, 0, len(seen))
	for _, s := range seen {
		out = append(out, *s)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].origName < out[j].origName })
	return out
}

func collectGoLocals(f *ir.IRFunc, paramSet map[string]bool) []string {
	seen := make(map[string]bool)
	var locals []string
	for _, blk := range f.Blocks {
		for _, instr := range blk.Instrs {
			if instr.Dst == "" || paramSet[instr.Dst] || seen[instr.Dst] {
				continue
			}
			switch instr.Op {
			case ir.OpLabel, ir.OpComment, ir.OpGoto, ir.OpReturn, ir.OpIf, ir.OpStore:
				continue
			}
			if strings.ContainsAny(instr.Dst, "(*") {
				continue
			}
			seen[instr.Dst] = true
			locals = append(locals, instr.Dst)
		}
	}
	sort.Strings(locals)
	return locals
}

func collectReferencedLabels(f *ir.IRFunc) map[string]bool {
	refs := make(map[string]bool)
	for _, blk := range f.Blocks {
		for _, instr := range blk.Instrs {
			switch instr.Op {
			case ir.OpGoto:
				refs[instr.Label] = true
			case ir.OpIf:
				refs[instr.Label] = true
				refs[instr.Label2] = true
			}
		}
	}
	return refs
}

func goFuncReturnType(f *ir.IRFunc) string {
	for _, blk := range f.Blocks {
		for _, instr := range blk.Instrs {
			if instr.Op != ir.OpReturn {
				continue
			}
			if len(instr.Src) == 0 {
				return ""
			}
			if len(instr.Src) == 1 {
				return goType(f.Vars[instr.Src[0]])
			}
			types := make([]string, len(instr.Src))
			for i, s := range instr.Src {
				types[i] = goType(f.Vars[s])
			}
			return "(" + strings.Join(types, ", ") + ")"
		}
	}
	return ""
}

func hasGoMain(fns []*ir.IRFunc) bool {
	for _, f := range fns {
		if goFuncShortName(f.Name) == "main" {
			return true
		}
	}
	return false
}

func goType(cType string) string {
	switch cType {
	case "int64_t", "":
		return "int64"
	case "uint64_t":
		return "uint64"
	case "int32_t":
		return "int32"
	case "uint32_t":
		return "uint32"
	case "void*", "*_type":
		return "unsafe.Pointer"
	case "GoString":
		return "string"
	case "GoSlice":
		return "[]byte"
	case "GoIface":
		return "any"
	case "error":
		return "error"
	default:
		return "int64"
	}
}

var goKeywords = map[string]bool{
	"break": true, "case": true, "chan": true, "const": true, "continue": true,
	"default": true, "defer": true, "else": true, "fallthrough": true, "for": true,
	"func": true, "go": true, "goto": true, "if": true, "import": true,
	"interface": true, "map": true, "package": true, "range": true, "return": true,
	"select": true, "struct": true, "switch": true, "type": true, "var": true,
}

func goFuncShortName(fullName string) string {
	if strings.HasPrefix(fullName, "(*") {
		s := strings.TrimPrefix(fullName, "(*")
		if i := strings.Index(s, ")"); i >= 0 {
			recv := s[:i]
			method := strings.TrimPrefix(s[i+1:], ".")
			if j := strings.LastIndex(recv, "."); j >= 0 {
				recv = recv[j+1:]
			}
			return sanitizeGoIdent(recv) + "_" + sanitizeGoIdent(method)
		}
	}
	name := fullName
	if i := strings.LastIndex(fullName, "."); i >= 0 {
		name = fullName[i+1:]
	}
	result := sanitizeGoIdent(name)
	// init is special in Go; avoid colliding with the runtime's init chain.
	if goKeywords[result] || result == "init" {
		result = "_" + result
	}
	return result
}

func goShortPkg(pkg string) string {
	if i := strings.LastIndex(pkg, "/"); i >= 0 {
		return pkg[i+1:]
	}
	return pkg
}

func goPackageDir(pkg string) string {
	if pkg == "" {
		return "unknown"
	}
	return pkg
}

func goCallName(target string) string {
	if strings.HasPrefix(target, "(*") {
		s := strings.TrimPrefix(target, "(*")
		if i := strings.Index(s, ")"); i >= 0 {
			recv := s[:i]
			method := strings.TrimPrefix(s[i+1:], ".")
			if j := strings.LastIndex(recv, "."); j >= 0 {
				recv = recv[j+1:]
			}
			return sanitizeGoIdent(recv) + "_" + sanitizeGoIdent(method)
		}
	}
	return sanitizeGoIdent(target)
}

func sanitizeGoIdent(s string) string {
	var sb strings.Builder
	for _, c := range s {
		if (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_' {
			sb.WriteRune(c)
		} else {
			sb.WriteByte('_')
		}
	}
	result := sb.String()
	if result == "" || (result[0] >= '0' && result[0] <= '9') {
		return "fn_" + result
	}
	return result
}

func goArithOp(meta string) string {
	switch meta {
	case "add":
		return "+"
	case "sub":
		return "-"
	case "mul":
		return "*"
	case "div":
		return "/"
	case "and":
		return "&"
	case "or":
		return "|"
	case "xor":
		return "^"
	case "shl", "sal":
		return "<<"
	case "shr", "sar":
		return ">>"
	default:
		return meta
	}
}

func goUnaryOp(meta string) string {
	switch meta {
	case "neg":
		return "-"
	case "not":
		return "^" // Go uses ^ for bitwise NOT, not ~
	default:
		return meta
	}
}
