package output

import (
	"fmt"
	"io"
	"strings"
)

// WriteGhidra emits a GhidraScript (Java) that renames functions to their
// pclntab names, applies pre-comments with behavior tags, and creates data
// type comments for recovered structs. Run via Ghidra's Script Manager.
func WriteGhidra(result *AnalysisResult, w io.Writer) error {
	fmt.Fprintln(w, "// Auto-generated by GoRipper v0.4.0")
	fmt.Fprintf(w, "// Binary: %s\n", result.BinaryInfo.Path)
	fmt.Fprintf(w, "// Arch:   %s  Format: %s\n", result.BinaryInfo.Arch, result.BinaryInfo.Format)
	fmt.Fprintln(w, "//")
	fmt.Fprintln(w, "// Run via Ghidra: Window > Script Manager > Run Script")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "//@category GoRipper")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "import ghidra.app.script.GhidraScript;")
	fmt.Fprintln(w, "import ghidra.program.model.address.Address;")
	fmt.Fprintln(w, "import ghidra.program.model.listing.Function;")
	fmt.Fprintln(w, "import ghidra.program.model.symbol.SourceType;")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "public class GoRipperRename extends GhidraScript {")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "    @Override")
	fmt.Fprintln(w, "    public void run() throws Exception {")
	fmt.Fprintln(w, "        int renamed = 0;")

	for _, fn := range result.Functions {
		if fn.FunctionSource != "pclntab" && fn.FunctionSource != "symbol_table" {
			continue
		}
		addr, err := parseHexAddr(fn.Addr)
		if err != nil {
			continue
		}

		safeName := ghidraSafeName(fn.Name)
		fmt.Fprintf(w, "        { // %s\n", fn.Name)
		fmt.Fprintf(w, "            Address a = toAddr(0x%xL);\n", addr)
		fmt.Fprintf(w, "            Function f = getFunctionAt(a);\n")
		fmt.Fprintln(w, "            if (f != null) {")
		fmt.Fprintf(w, "                f.setName(%q, SourceType.USER_DEFINED);\n", safeName)

		if len(fn.Tags) > 0 {
			comment := "GoRipper: " + strings.Join(fn.Tags, ", ")
			fmt.Fprintf(w, "                setPreComment(a, %q);\n", comment)
		}

		fmt.Fprintln(w, "                renamed++;")
		fmt.Fprintln(w, "            }")
		fmt.Fprintln(w, "        }")
	}

	for _, t := range result.Types {
		if t.Kind != "struct" || len(t.Fields) == 0 {
			continue
		}
		fmt.Fprintf(w, "        // struct %s (%d fields)\n", t.Name, len(t.Fields))
		for _, f := range t.Fields {
			fmt.Fprintf(w, "        //   +0x%x %s %s\n", f.Offset, f.Type, f.Name)
		}
	}

	fmt.Fprintln(w, "        println(\"[GoRipper] renamed \" + renamed + \" functions\");")
	fmt.Fprintln(w, "    }")
	fmt.Fprintln(w, "}")
	return nil
}

func ghidraSafeName(name string) string {
	var sb strings.Builder
	for i, r := range name {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
			sb.WriteRune(r)
		case r == '_':
			sb.WriteByte('_')
		case r == '.':
			sb.WriteByte('_')
		case r == '/':
			sb.WriteByte('_')
		case r == '*':
			if i > 0 {
				sb.WriteString("_ptr")
			}
		case r == '(' || r == ')':
			// skip
		default:
			sb.WriteByte('_')
		}
	}
	result := sb.String()
	if len(result) > 0 && result[0] >= '0' && result[0] <= '9' {
		result = "_" + result
	}
	return result
}
