package output

import (
	"fmt"
	"io"
	"strings"

	"github.com/muxover/goripper/internal/version"
)

// WriteIDA emits an IDAPython script that renames functions to their pclntab
// names, applies behavior tags as repeatable comments, and marks concurrent
// functions with bookmarks.
func WriteIDA(result *AnalysisResult, w io.Writer) error {
	fmt.Fprintf(w, "# Auto-generated by GoRipper %s\n", version.Version)
	fmt.Fprintf(w, "# Binary: %s\n", result.BinaryInfo.Path)
	fmt.Fprintf(w, "# Arch:   %s  Format: %s\n", result.BinaryInfo.Arch, result.BinaryInfo.Format)
	fmt.Fprintln(w, "#")
	fmt.Fprintln(w, "# Run via: File > Script file... (or idc.RunScript)")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "import idc, idaapi, idautils")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "def apply_goripper():")

	count := 0
	for _, fn := range result.Functions {
		if fn.FunctionSource != "pclntab" && fn.FunctionSource != "symbol_table" {
			continue
		}
		addr, err := parseHexAddr(fn.Addr)
		if err != nil {
			continue
		}

		safeName := idaSafeName(fn.Name)
		fmt.Fprintf(w, "    idc.set_name(0x%x, %q, idc.SN_NOWARN)\n", addr, safeName)

		if len(fn.Tags) > 0 {
			comment := "GoRipper: " + strings.Join(fn.Tags, ", ")
			fmt.Fprintf(w, "    idc.set_cmt(0x%x, %q, 1)\n", addr, comment)
		}

		if fn.IsConcurrent {
			fmt.Fprintf(w, "    idaapi.add_bookmark(0x%x, \"goroutine\", %q, 0)\n",
				addr, fn.Name)
		}
		count++
	}

	if count == 0 {
		fmt.Fprintln(w, "    pass  # no pclntab functions found")
	}

	fmt.Fprintln(w)
	fmt.Fprintf(w, "    print(\"[GoRipper] applied %d function names\")\n", count)
	fmt.Fprintln(w)
	fmt.Fprintln(w, "apply_goripper()")
	return nil
}

// idaSafeName converts a Go function name to a valid IDA identifier.
// IDA allows alphanumerics and underscores; dots and slashes are replaced.
func idaSafeName(name string) string {
	var sb strings.Builder
	for _, r := range name {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9', r == '_':
			sb.WriteRune(r)
		case r == '.':
			sb.WriteByte('_')
		case r == '/':
			sb.WriteByte('_')
		case r == '*':
			sb.WriteString("ptr_")
		case r == '(':
			// skip
		case r == ')':
			// skip
		default:
			sb.WriteByte('_')
		}
	}
	return sb.String()
}

func parseHexAddr(s string) (uint64, error) {
	var addr uint64
	if len(s) > 2 && s[:2] == "0x" {
		s = s[2:]
	}
	for _, c := range s {
		addr <<= 4
		switch {
		case c >= '0' && c <= '9':
			addr |= uint64(c - '0')
		case c >= 'a' && c <= 'f':
			addr |= uint64(c-'a') + 10
		case c >= 'A' && c <= 'F':
			addr |= uint64(c-'A') + 10
		default:
			return 0, fmt.Errorf("invalid hex: %s", s)
		}
	}
	return addr, nil
}
