package main

import "github.com/spf13/cobra"

// registerCompletions attaches shell completion hints to commands.
// The completion subcommand itself is auto-generated by cobra — no newCompletionCmd needed.
func registerCompletions(analyze, functions, stringsCmd, callgraph, diffCmd, compareCmd, scandirCmd *cobra.Command) {
	fileArg := func(cmd *cobra.Command, args []string, _ string) ([]string, cobra.ShellCompDirective) {
		if len(args) >= 1 {
			return nil, cobra.ShellCompDirectiveNoFileComp
		}
		return nil, cobra.ShellCompDirectiveDefault
	}
	for _, cmd := range []*cobra.Command{analyze, functions, stringsCmd, callgraph} {
		cmd.ValidArgsFunction = fileArg
	}

	twoFileArg := func(cmd *cobra.Command, args []string, _ string) ([]string, cobra.ShellCompDirective) {
		if len(args) >= 2 {
			return nil, cobra.ShellCompDirectiveNoFileComp
		}
		return nil, cobra.ShellCompDirectiveDefault
	}
	diffCmd.ValidArgsFunction = twoFileArg
	compareCmd.ValidArgsFunction = twoFileArg

	// scan-dir takes a directory argument
	scandirCmd.ValidArgsFunction = func(cmd *cobra.Command, args []string, _ string) ([]string, cobra.ShellCompDirective) {
		if len(args) >= 1 {
			return nil, cobra.ShellCompDirectiveNoFileComp
		}
		return nil, cobra.ShellCompDirectiveFilterDirs
	}

	_ = stringsCmd.RegisterFlagCompletionFunc("type",
		func(_ *cobra.Command, _ []string, _ string) ([]string, cobra.ShellCompDirective) {
			return []string{"url", "ip", "path", "secret", "pkgpath"}, cobra.ShellCompDirectiveNoFileComp
		})
}
