package main

import "github.com/spf13/cobra"

// registerCompletions attaches shell completion hints to commands.
// The `completion` subcommand itself is auto-generated by cobra.
func registerCompletions(analyze, functions, stringsCmd, callgraph, diffCmd *cobra.Command) {
	// Binary path arg: default file completion, reject extra args.
	fileArg := func(cmd *cobra.Command, args []string, _ string) ([]string, cobra.ShellCompDirective) {
		if len(args) >= 1 {
			return nil, cobra.ShellCompDirectiveNoFileComp
		}
		return nil, cobra.ShellCompDirectiveDefault
	}
	for _, cmd := range []*cobra.Command{analyze, functions, stringsCmd, callgraph} {
		cmd.ValidArgsFunction = fileArg
	}

	// diff takes two binary paths.
	diffCmd.ValidArgsFunction = func(cmd *cobra.Command, args []string, _ string) ([]string, cobra.ShellCompDirective) {
		if len(args) >= 2 {
			return nil, cobra.ShellCompDirectiveNoFileComp
		}
		return nil, cobra.ShellCompDirectiveDefault
	}

	// --type on strings: complete known classifier values.
	_ = stringsCmd.RegisterFlagCompletionFunc("type",
		func(_ *cobra.Command, _ []string, _ string) ([]string, cobra.ShellCompDirective) {
			return []string{"url", "ip", "path", "secret", "pkgpath"}, cobra.ShellCompDirectiveNoFileComp
		})
}
